# Generated by Django 4.2.1 on 2023-05-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seance',
            old_name='module',
            new_name='subject',
        ),
    ]
