# Generated by Django 4.2.1 on 2023-05-23 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_remove_formation_semesters_formation_nb_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='time',
        ),
        migrations.AddField(
            model_name='seance',
            name='end_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='seance',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
