# Generated by Django 4.2.1 on 2023-05-27 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_remove_seance_time_seance_end_time_seance_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.grade'),
        ),
        migrations.AlterField(
            model_name='salle',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.typesalle'),
        ),
    ]
