# Generated by Django 4.2.1 on 2023-05-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_grade_typesalle_alter_enseignant_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='volume',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='daily_load',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='module',
            name='weekly_volume',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='semestre',
            name='session',
            field=models.CharField(choices=[('février', 'Février'), ('juin', 'Juin')], default='février', max_length=10),
        ),
        migrations.AlterField(
            model_name='salle',
            name='type',
            field=models.CharField(choices=[('td', 'TD'), ('tp', 'TP'), ('amphitheater', 'Amphitheater')], max_length=15),
        ),
        migrations.AlterField(
            model_name='seance',
            name='type',
            field=models.CharField(choices=[('td', 'TD'), ('tp', 'TP'), ('cours', 'Cours')], max_length=10),
        ),
        migrations.DeleteModel(
            name='TypeSalle',
        ),
    ]
