# Generated by Django 4.2.1 on 2023-06-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_alter_formation_name_alter_grade_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formation',
            name='niveau',
            field=models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='formation',
            unique_together={('name', 'niveau')},
        ),
    ]
