# Generated by Django 4.2.1 on 2023-06-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_formation_name_alter_formation_niveau_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='formation',
            constraint=models.UniqueConstraint(fields=('name', 'niveau'), name='unique_name_niveau'),
        ),
    ]
