# Generated by Django 4.2.1 on 2023-06-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_alter_formation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
